[0m15:01:10.669743 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105b23860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1046db9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105da6f60>]}


============================== 15:01:10.679365 | 2ebd362e-0102-4dc3-bb89-a3a34ee60036 ==============================
[0m15:01:10.679365 [info ] [MainThread]: Running with dbt=1.10.9
[0m15:01:10.680508 [debug] [MainThread]: running dbt with arguments {'write_json': 'True', 'version_check': 'True', 'use_experimental_parser': 'False', 'invocation_command': 'dbt ls --resource-type model --output json', 'profiles_dir': '/Users/vongly/.dbt', 'static_parser': 'True', 'fail_fast': 'False', 'introspect': 'True', 'quiet': 'False', 'partial_parse': 'True', 'warn_error': 'None', 'log_format': 'default', 'printer_width': '80', 'debug': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'target_path': 'None', 'log_cache_events': 'False', 'cache_selected_only': 'False', 'use_colors': 'True', 'empty': 'None', 'send_anonymous_usage_stats': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'no_print': 'None'}
[0m15:01:10.681599 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/vongly/dev/freelance/MoveUnited/usawfl/orchestrate/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:01:10.685694 [debug] [MainThread]: Resource report: {"command_name": "list", "command_success": false, "command_wall_clock_time": 0.124007754, "process_in_blocks": "0", "process_kernel_time": 0.367801, "process_mem_max_rss": "96743424", "process_out_blocks": "0", "process_user_time": 1.988547}
[0m15:01:10.687823 [debug] [MainThread]: Command `dbt ls` failed at 15:01:10.687454 after 0.13 seconds
[0m15:01:10.689159 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105c15280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056c6630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054dcef0>]}
[0m15:01:10.689910 [debug] [MainThread]: Flushing usage events
[0m15:01:11.169025 [debug] [MainThread]: An error was encountered while trying to flush usage events
